# Generated by Django 2.2.4 on 2019-10-06 14:39

from django.db import migrations
import phonenumbers


def normalize_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if not phonenumbers.is_valid_number(phone):
            continue
        flat.owner_phone_pure = f'+{phone.country_code}{phone.national_number}'
        flat.save()


def move_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(normalize_phones, move_backward),
    ]
