# Generated by Django 2.2.4 on 2019-10-06 14:48

from django.db import migrations


def move_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            owner_name=flat.owner_deprecated,
            owner_phone=flat.owners_phonenumber,
            owner_phone_pure=flat.owner_phone_pure
        )
        if flat not in owner.owner_flats.all():
            owner.owner_flats.add(flat)


def move_backwards(app, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20191006_1746'),
    ]

    operations = [
        migrations.RunPython(move_owners, move_backwards),
    ]
